package com.worldbestsoft.model;

// Generated Sep 9, 2013 10:21:54 AM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DocumentSeq generated by hbm2java
 */
@Entity
@Table(name = "document_seq", catalog = "onion", uniqueConstraints = @UniqueConstraint(columnNames = "type"))
public class DocumentSeq implements java.io.Serializable {

	private Long id;
	private String type;
	private Long currentVal;
	private Date updateDate;

	public DocumentSeq() {
	}

	public DocumentSeq(String type) {
		this.type = type;
	}

	public DocumentSeq(String type, Long currentVal, Date updateDate) {
		this.type = type;
		this.currentVal = currentVal;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "type", unique = true, nullable = false, length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "current_val")
	public Long getCurrentVal() {
		return this.currentVal;
	}

	public void setCurrentVal(Long currentVal) {
		this.currentVal = currentVal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Override
    public String toString() {
	    StringBuilder builder = new StringBuilder();
	    builder.append("DocumentSeq [id=");
	    builder.append(id);
	    builder.append(", type=");
	    builder.append(type);
	    builder.append(", currentVal=");
	    builder.append(currentVal);
	    builder.append(", updateDate=");
	    builder.append(updateDate);
	    builder.append("]");
	    return builder.toString();
    }

	@Override
    public int hashCode() {
	    final int prime = 31;
	    int result = 1;
	    result = prime * result + ((id == null) ? 0 : id.hashCode());
	    return result;
    }

	@Override
    public boolean equals(Object obj) {
	    if (this == obj)
		    return true;
	    if (obj == null)
		    return false;
	    if (getClass() != obj.getClass())
		    return false;
	    DocumentSeq other = (DocumentSeq) obj;
	    if (id == null) {
		    if (other.id != null)
			    return false;
	    } else if (!id.equals(other.id))
		    return false;
	    return true;
    }

	
}
