package com.worldbestsoft.model;

// Generated Jul 24, 2013 12:30:26 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DocumentNumber generated by hbm2java
 */
@Entity
@Table(name = "document_number", catalog = "onion", uniqueConstraints = @UniqueConstraint(columnNames = "type"))
public class DocumentNumber implements java.io.Serializable {

	private Long id;
	private String type;
	private Long currentVal;
	private Date updateDate;

	public DocumentNumber() {
	}

	public DocumentNumber(String type) {
		this.type = type;
	}

	public DocumentNumber(String type, Long currentVal, Date updateDate) {
		this.type = type;
		this.currentVal = currentVal;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "type", unique = true, nullable = false, length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "current_val")
	public Long getCurrentVal() {
		return this.currentVal;
	}

	public void setCurrentVal(Long currentVal) {
		this.currentVal = currentVal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
