package com.worldbestsoft.model;

// Generated Jul 23, 2013 9:54:03 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InvGoodsMovementItem generated by hbm2java
 */
@Entity
@Table(name = "inv_goods_movement_item", catalog = "onion")
public class InvGoodsMovementItem implements java.io.Serializable {

	private Long id;
	private InvGoodsMovement invGoodsMovement;
	private InvItem invItem;
	private BigDecimal qty;
	private String memo;

	public InvGoodsMovementItem() {
	}

	public InvGoodsMovementItem(InvGoodsMovement invGoodsMovement, InvItem invItem) {
		this.invGoodsMovement = invGoodsMovement;
		this.invItem = invItem;
	}

	public InvGoodsMovementItem(InvGoodsMovement invGoodsMovement, InvItem invItem, BigDecimal qty, String memo) {
		this.invGoodsMovement = invGoodsMovement;
		this.invItem = invItem;
		this.qty = qty;
		this.memo = memo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inv_goods_movement_id", nullable = false)
	public InvGoodsMovement getInvGoodsMovement() {
		return this.invGoodsMovement;
	}

	public void setInvGoodsMovement(InvGoodsMovement invGoodsMovement) {
		this.invGoodsMovement = invGoodsMovement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inv_item_id", nullable = false)
	public InvItem getInvItem() {
		return this.invItem;
	}

	public void setInvItem(InvItem invItem) {
		this.invItem = invItem;
	}

	@Column(name = "qty", precision = 10)
	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	@Column(name = "memo", length = 50)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
