package com.worldbestsoft.model;

// Generated Jul 23, 2013 9:54:03 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvGoodsMovement generated by hbm2java
 */
@Entity
@Table(name = "inv_goods_movement", catalog = "onion")
public class InvGoodsMovement implements java.io.Serializable {

	private Long id;
	private String runningNo;
	private Date movementDate;
	private String movementType;
	private String owner;
	private Date createDate;
	private String createUser;
	private Date updateDate;
	private String updateUser;
	private Set<InvGoodsMovementItem> invGoodsMovementItems = new HashSet<InvGoodsMovementItem>(0);

	public InvGoodsMovement() {
	}

	public InvGoodsMovement(String runningNo, Date movementDate, String movementType, String owner, Date createDate, String createUser, Date updateDate, String updateUser, Set<InvGoodsMovementItem> invGoodsMovementItems) {
		this.runningNo = runningNo;
		this.movementDate = movementDate;
		this.movementType = movementType;
		this.owner = owner;
		this.createDate = createDate;
		this.createUser = createUser;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
		this.invGoodsMovementItems = invGoodsMovementItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "running_no", length = 20)
	public String getRunningNo() {
		return this.runningNo;
	}

	public void setRunningNo(String runningNo) {
		this.runningNo = runningNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "movement_date", length = 19)
	public Date getMovementDate() {
		return this.movementDate;
	}

	public void setMovementDate(Date movementDate) {
		this.movementDate = movementDate;
	}

	@Column(name = "movement_type", length = 3)
	public String getMovementType() {
		return this.movementType;
	}

	public void setMovementType(String movementType) {
		this.movementType = movementType;
	}

	@Column(name = "owner", length = 50)
	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "create_user", length = 50)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "update_user", length = 50)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invGoodsMovement")
	public Set<InvGoodsMovementItem> getInvGoodsMovementItems() {
		return this.invGoodsMovementItems;
	}

	public void setInvGoodsMovementItems(Set<InvGoodsMovementItem> invGoodsMovementItems) {
		this.invGoodsMovementItems = invGoodsMovementItems;
	}

}
