package com.worldbestsoft.model;

// Generated Jul 16, 2013 3:46:49 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InvGoodReceiptItem generated by hbm2java
 */
@Entity
@Table(name = "inv_good_receipt_item", catalog = "onion")
public class InvGoodsReceiptItem implements java.io.Serializable {

	private Long id;
	private InvGoodsReceipt invGoodReceipt;
	private InvItem invItem;
	private Integer qty;
	private BigDecimal unitPrice;
	private BigDecimal unitType;
	private String memo;

	public InvGoodsReceiptItem() {
	}

	public InvGoodsReceiptItem(InvGoodsReceipt invGoodReceipt, InvItem invItem) {
		this.invGoodReceipt = invGoodReceipt;
		this.invItem = invItem;
	}

	public InvGoodsReceiptItem(InvGoodsReceipt invGoodReceipt, InvItem invItem, Integer qty, BigDecimal unitPrice, BigDecimal unitType, String memo) {
		this.invGoodReceipt = invGoodReceipt;
		this.invItem = invItem;
		this.qty = qty;
		this.unitPrice = unitPrice;
		this.unitType = unitType;
		this.memo = memo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inv_good_receipt_id", nullable = false)
	public InvGoodsReceipt getInvGoodReceipt() {
		return this.invGoodReceipt;
	}

	public void setInvGoodReceipt(InvGoodsReceipt invGoodReceipt) {
		this.invGoodReceipt = invGoodReceipt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inv_item_id", nullable = false)
	public InvItem getInvItem() {
		return this.invItem;
	}

	public void setInvItem(InvItem invItem) {
		this.invItem = invItem;
	}

	@Column(name = "qty")
	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	@Column(name = "unit_price", precision = 10)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "unit_type", precision = 10)
	public BigDecimal getUnitType() {
		return this.unitType;
	}

	public void setUnitType(BigDecimal unitType) {
		this.unitType = unitType;
	}

	@Column(name = "memo")
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
