package com.worldbestsoft.model;

// Generated Jul 26, 2013 1:18:48 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InvGoodsReceiptItem generated by hbm2java
 */
@Entity
@Table(name = "inv_goods_receipt_item", catalog = "onion")
public class InvGoodsReceiptItem implements java.io.Serializable {

	private Long id;
	private InvGoodsReceipt invGoodsReceipt;
	private InvItem invItem;
	private BigDecimal qty;
	private BigDecimal unitPrice;
	private String unitType;
	private String memo;

	public InvGoodsReceiptItem() {
	}

	public InvGoodsReceiptItem(InvGoodsReceipt invGoodsReceipt, InvItem invItem) {
		this.invGoodsReceipt = invGoodsReceipt;
		this.invItem = invItem;
	}

	public InvGoodsReceiptItem(InvGoodsReceipt invGoodsReceipt, InvItem invItem, BigDecimal qty, BigDecimal unitPrice, String unitType, String memo) {
		this.invGoodsReceipt = invGoodsReceipt;
		this.invItem = invItem;
		this.qty = qty;
		this.unitPrice = unitPrice;
		this.unitType = unitType;
		this.memo = memo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inv_goods_receipt_id", nullable = false)
	public InvGoodsReceipt getInvGoodsReceipt() {
		return this.invGoodsReceipt;
	}

	public void setInvGoodsReceipt(InvGoodsReceipt invGoodsReceipt) {
		this.invGoodsReceipt = invGoodsReceipt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inv_item_id", nullable = false)
	public InvItem getInvItem() {
		return this.invItem;
	}

	public void setInvItem(InvItem invItem) {
		this.invItem = invItem;
	}

	@Column(name = "qty", precision = 10)
	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	@Column(name = "unit_price", precision = 10)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "unit_type", length = 3)
	public String getUnitType() {
		return this.unitType;
	}

	public void setUnitType(String unitType) {
		this.unitType = unitType;
	}

	@Column(name = "memo")
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
