package com.worldbestsoft.model;

// Generated Jul 16, 2013 3:46:49 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvGoodMovementItem generated by hbm2java
 */
@Entity
@Table(name = "inv_good_movement_item", catalog = "onion")
public class InvGoodMovementItem implements java.io.Serializable {

	private Integer id;
	private InvGoodMovement invGoodMovement;
	private InvItem invItem;
	private Integer qty;
	private String owner;
	private String memo;
	private String movementType;
	private Date createDate;
	private String createUser;
	private Date updateDate;
	private String updateUser;

	public InvGoodMovementItem() {
	}

	public InvGoodMovementItem(InvGoodMovement invGoodMovement, InvItem invItem) {
		this.invGoodMovement = invGoodMovement;
		this.invItem = invItem;
	}

	public InvGoodMovementItem(InvGoodMovement invGoodMovement, InvItem invItem, Integer qty, String owner, String memo, String movementType, Date createDate, String createUser, Date updateDate, String updateUser) {
		this.invGoodMovement = invGoodMovement;
		this.invItem = invItem;
		this.qty = qty;
		this.owner = owner;
		this.memo = memo;
		this.movementType = movementType;
		this.createDate = createDate;
		this.createUser = createUser;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inv_good_movement_id", nullable = false)
	public InvGoodMovement getInvGoodMovement() {
		return this.invGoodMovement;
	}

	public void setInvGoodMovement(InvGoodMovement invGoodMovement) {
		this.invGoodMovement = invGoodMovement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inv_item_id", nullable = false)
	public InvItem getInvItem() {
		return this.invItem;
	}

	public void setInvItem(InvItem invItem) {
		this.invItem = invItem;
	}

	@Column(name = "qty")
	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	@Column(name = "owner", length = 50)
	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	@Column(name = "memo", length = 50)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Column(name = "movement_type", length = 3)
	public String getMovementType() {
		return this.movementType;
	}

	public void setMovementType(String movementType) {
		this.movementType = movementType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "create_user", length = 50)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "update_user", length = 50)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

}
