package com.worldbestsoft.model;

// Generated Sep 9, 2013 10:54:50 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Collection;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvGoodsReceipt generated by hbm2java
 */
@Entity
@Table(name = "inv_goods_receipt", catalog = "onion")
public class InvGoodsReceipt implements java.io.Serializable {

	private Long id;
	private Supplier supplier;
	private DocumentNumber documentNumber;
	private Date receiptDate;
	private String receiptType;
	private BigDecimal totalCost;
	private String memo;
	private Date createDate;
	private String createUser;
	private Date updateDate;
	private String updateUser;
	private Set<InvGoodsReceiptItem> invGoodsReceiptItems = new HashSet<InvGoodsReceiptItem>(0);

	public InvGoodsReceipt() {
	}

	public InvGoodsReceipt(Supplier supplier, DocumentNumber documentNumber, Date receiptDate, String receiptType, BigDecimal totalCost, String memo, Date createDate, String createUser, Date updateDate, String updateUser, Set<InvGoodsReceiptItem> invGoodsReceiptItems) {
		this.supplier = supplier;
		this.documentNumber = documentNumber;
		this.receiptDate = receiptDate;
		this.receiptType = receiptType;
		this.totalCost = totalCost;
		this.memo = memo;
		this.createDate = createDate;
		this.createUser = createUser;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
		this.invGoodsReceiptItems = invGoodsReceiptItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "supplier_id")
	public Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "document_number_internal_no")
	public DocumentNumber getDocumentNumber() {
		return this.documentNumber;
	}

	public void setDocumentNumber(DocumentNumber documentNumber) {
		this.documentNumber = documentNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "receipt_date", length = 19)
	public Date getReceiptDate() {
		return this.receiptDate;
	}

	public void setReceiptDate(Date receiptDate) {
		this.receiptDate = receiptDate;
	}

	@Column(name = "receipt_type", length = 3)
	public String getReceiptType() {
		return this.receiptType;
	}

	public void setReceiptType(String receiptType) {
		this.receiptType = receiptType;
	}

	@Column(name = "total_cost", precision = 10)
	public BigDecimal getTotalCost() {
		return this.totalCost;
	}

	public void setTotalCost(BigDecimal totalCost) {
		this.totalCost = totalCost;
	}

	@Column(name = "memo")
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "create_user", length = 50)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "update_user", length = 50)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invGoodsReceipt")
	public Set<InvGoodsReceiptItem> getInvGoodsReceiptItems() {
		return this.invGoodsReceiptItems;
	}

	public void setInvGoodsReceiptItems(Set<InvGoodsReceiptItem> invGoodsReceiptItems) {
		this.invGoodsReceiptItems = invGoodsReceiptItems;
	}

	@Override
    public String toString() {
	    final int maxLen = 10;
	    StringBuilder builder = new StringBuilder();
	    builder.append("InvGoodsReceipt [id=");
	    builder.append(id);
	    builder.append(", supplier=");
	    builder.append(supplier);
	    builder.append(", documentNumber=");
	    builder.append(documentNumber);
	    builder.append(", receiptDate=");
	    builder.append(receiptDate);
	    builder.append(", receiptType=");
	    builder.append(receiptType);
	    builder.append(", totalCost=");
	    builder.append(totalCost);
	    builder.append(", memo=");
	    builder.append(memo);
	    builder.append(", createDate=");
	    builder.append(createDate);
	    builder.append(", createUser=");
	    builder.append(createUser);
	    builder.append(", updateDate=");
	    builder.append(updateDate);
	    builder.append(", updateUser=");
	    builder.append(updateUser);
	    builder.append("]");
	    return builder.toString();
    }

	@Override
    public int hashCode() {
	    final int prime = 31;
	    int result = 1;
	    result = prime * result + ((id == null) ? 0 : id.hashCode());
	    return result;
    }

	@Override
    public boolean equals(Object obj) {
	    if (this == obj)
		    return true;
	    if (obj == null)
		    return false;
	    if (getClass() != obj.getClass())
		    return false;
	    InvGoodsReceipt other = (InvGoodsReceipt) obj;
	    if (id == null) {
		    if (other.id != null)
			    return false;
	    } else if (!id.equals(other.id))
		    return false;
	    return true;
    }

	
}
