package com.worldbestsoft.model;

// Generated Sep 9, 2013 10:54:50 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvItemLevel generated by hbm2java
 */
@Entity
@Table(name = "inv_item_level", catalog = "onion")
public class InvItemLevel implements java.io.Serializable {

	private Long id;
	private DocumentNumber documentNumber;
	private InvItem invItem;
	private Date transactionDate;
	private BigDecimal qtyBefore;
	private BigDecimal qtyAdjust;
	private BigDecimal qtyAfter;
	private BigDecimal qtyAvailableBefore;
	private BigDecimal qtyAvailableAdjust;
	private BigDecimal qtyAvailableAfter;
	private String refType;
	private String transactionType;
	private String updateUser;

	public InvItemLevel() {
	}

	public InvItemLevel(InvItem invItem, Date transactionDate) {
		this.invItem = invItem;
		this.transactionDate = transactionDate;
	}

	public InvItemLevel(DocumentNumber documentNumber, InvItem invItem, Date transactionDate, BigDecimal qtyBefore, BigDecimal qtyAdjust, BigDecimal qtyAfter, BigDecimal qtyAvailableBefore, BigDecimal qtyAvailableAdjust, BigDecimal qtyAvailableAfter, String refType, String transactionType, String updateUser) {
		this.documentNumber = documentNumber;
		this.invItem = invItem;
		this.transactionDate = transactionDate;
		this.qtyBefore = qtyBefore;
		this.qtyAdjust = qtyAdjust;
		this.qtyAfter = qtyAfter;
		this.qtyAvailableBefore = qtyAvailableBefore;
		this.qtyAvailableAdjust = qtyAvailableAdjust;
		this.qtyAvailableAfter = qtyAvailableAfter;
		this.refType = refType;
		this.transactionType = transactionType;
		this.updateUser = updateUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "document_number_internal_no")
	public DocumentNumber getDocumentNumber() {
		return this.documentNumber;
	}

	public void setDocumentNumber(DocumentNumber documentNumber) {
		this.documentNumber = documentNumber;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inv_item_id", nullable = false)
	public InvItem getInvItem() {
		return this.invItem;
	}

	public void setInvItem(InvItem invItem) {
		this.invItem = invItem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "transaction_date", nullable = false, length = 19)
	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	@Column(name = "qty_before", precision = 10)
	public BigDecimal getQtyBefore() {
		return this.qtyBefore;
	}

	public void setQtyBefore(BigDecimal qtyBefore) {
		this.qtyBefore = qtyBefore;
	}

	@Column(name = "qty_adjust", precision = 10)
	public BigDecimal getQtyAdjust() {
		return this.qtyAdjust;
	}

	public void setQtyAdjust(BigDecimal qtyAdjust) {
		this.qtyAdjust = qtyAdjust;
	}

	@Column(name = "qty_after", precision = 10)
	public BigDecimal getQtyAfter() {
		return this.qtyAfter;
	}

	public void setQtyAfter(BigDecimal qtyAfter) {
		this.qtyAfter = qtyAfter;
	}

	@Column(name = "qty_available_before", precision = 10)
	public BigDecimal getQtyAvailableBefore() {
		return this.qtyAvailableBefore;
	}

	public void setQtyAvailableBefore(BigDecimal qtyAvailableBefore) {
		this.qtyAvailableBefore = qtyAvailableBefore;
	}

	@Column(name = "qty_available_adjust", precision = 10)
	public BigDecimal getQtyAvailableAdjust() {
		return this.qtyAvailableAdjust;
	}

	public void setQtyAvailableAdjust(BigDecimal qtyAvailableAdjust) {
		this.qtyAvailableAdjust = qtyAvailableAdjust;
	}

	@Column(name = "qty_available_after", precision = 10)
	public BigDecimal getQtyAvailableAfter() {
		return this.qtyAvailableAfter;
	}

	public void setQtyAvailableAfter(BigDecimal qtyAvailableAfter) {
		this.qtyAvailableAfter = qtyAvailableAfter;
	}

	@Column(name = "ref_type", length = 3)
	public String getRefType() {
		return this.refType;
	}

	public void setRefType(String refType) {
		this.refType = refType;
	}

	@Column(name = "transaction_type", length = 3)
	public String getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	@Column(name = "update_user", length = 50)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

}
