package com.worldbestsoft.model;

// Generated Jul 24, 2013 12:06:40 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SaleOrderItem generated by hbm2java
 */
@Entity
@Table(name = "sale_order_item", catalog = "onion")
public class SaleOrderItem implements java.io.Serializable {

	private Long id;
	private SaleOrder saleOrder;
	private Catalog catalog;
	private BigDecimal qty;
	private BigDecimal pricePerUnit;
	private BigDecimal price;
	private Date createDate;
	private String createUser;
	private Date updateDate;
	private String updateUser;
	private Set<JobOrder> jobOrders = new HashSet<JobOrder>(0);

	public SaleOrderItem() {
	}

	public SaleOrderItem(SaleOrder saleOrder, Catalog catalog) {
		this.saleOrder = saleOrder;
		this.catalog = catalog;
	}

	public SaleOrderItem(SaleOrder saleOrder, Catalog catalog, BigDecimal qty, BigDecimal pricePerUnit, BigDecimal price, Date createDate, String createUser, Date updateDate, String updateUser, Set<JobOrder> jobOrders) {
		this.saleOrder = saleOrder;
		this.catalog = catalog;
		this.qty = qty;
		this.pricePerUnit = pricePerUnit;
		this.price = price;
		this.createDate = createDate;
		this.createUser = createUser;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
		this.jobOrders = jobOrders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sale_order_id", nullable = false)
	public SaleOrder getSaleOrder() {
		return this.saleOrder;
	}

	public void setSaleOrder(SaleOrder saleOrder) {
		this.saleOrder = saleOrder;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "catalog_id", nullable = false)
	public Catalog getCatalog() {
		return this.catalog;
	}

	public void setCatalog(Catalog catalog) {
		this.catalog = catalog;
	}

	@Column(name = "qty", precision = 10)
	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	@Column(name = "price_per_unit", precision = 10)
	public BigDecimal getPricePerUnit() {
		return this.pricePerUnit;
	}

	public void setPricePerUnit(BigDecimal pricePerUnit) {
		this.pricePerUnit = pricePerUnit;
	}

	@Column(name = "price", precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "create_user", length = 50)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "update_user", length = 50)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "saleOrderItem")
	public Set<JobOrder> getJobOrders() {
		return this.jobOrders;
	}

	public void setJobOrders(Set<JobOrder> jobOrders) {
		this.jobOrders = jobOrders;
	}

}
