package com.worldbestsoft.model;

// Generated Jul 24, 2013 12:06:40 PM by Hibernate Tools 4.0.0

import java.util.Collection;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.search.annotations.Analyze;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.Store;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "supplier", catalog = "onion", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
@Indexed
public class Supplier implements java.io.Serializable {

	private Long id;
	@Field(index=Index.YES, analyze=Analyze.YES, store=Store.NO)
	private String code;
	@Field(index=Index.YES, analyze=Analyze.YES, store=Store.NO)
	private String name;
	private String address;
	private String contactName;
	private String contactTel;
	private Date createDate;
	private String createUser;
	private Date updateDate;
	private String updateUser;
	private Set<InvGoodsReceipt> invGoodsReceipts = new HashSet<InvGoodsReceipt>(0);

	public Supplier() {
	}

	public Supplier(String code, String name) {
		this.code = code;
		this.name = name;
	}

	public Supplier(String code, String name, String address, String contactName, String contactTel, Date createDate, String createUser, Date updateDate, String updateUser, Set<InvGoodsReceipt> invGoodsReceipts) {
		this.code = code;
		this.name = name;
		this.address = address;
		this.contactName = contactName;
		this.contactTel = contactTel;
		this.createDate = createDate;
		this.createUser = createUser;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
		this.invGoodsReceipts = invGoodsReceipts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "code", unique = true, nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "contact_name", length = 50)
	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	@Column(name = "contact_tel", length = 50)
	public String getContactTel() {
		return this.contactTel;
	}

	public void setContactTel(String contactTel) {
		this.contactTel = contactTel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "create_user", length = 50)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "update_user", length = 50)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public Set<InvGoodsReceipt> getInvGoodsReceipts() {
		return this.invGoodsReceipts;
	}

	public void setInvGoodsReceipts(Set<InvGoodsReceipt> invGoodsReceipts) {
		this.invGoodsReceipts = invGoodsReceipts;
	}

	@Override
    public String toString() {
	    final int maxLen = 10;
	    StringBuilder builder = new StringBuilder();
	    builder.append("Supplier [id=");
	    builder.append(id);
	    builder.append(", code=");
	    builder.append(code);
	    builder.append(", name=");
	    builder.append(name);
	    builder.append(", address=");
	    builder.append(address);
	    builder.append(", contactName=");
	    builder.append(contactName);
	    builder.append(", contactTel=");
	    builder.append(contactTel);
	    builder.append(", createDate=");
	    builder.append(createDate);
	    builder.append(", createUser=");
	    builder.append(createUser);
	    builder.append(", updateDate=");
	    builder.append(updateDate);
	    builder.append(", updateUser=");
	    builder.append(updateUser);
	    builder.append("]");
	    return builder.toString();
    }

	@Override
    public int hashCode() {
	    final int prime = 31;
	    int result = 1;
	    result = prime * result + ((id == null) ? 0 : id.hashCode());
	    return result;
    }

	@Override
    public boolean equals(Object obj) {
	    if (this == obj)
		    return true;
	    if (obj == null)
		    return false;
	    if (getClass() != obj.getClass())
		    return false;
	    Supplier other = (Supplier) obj;
	    if (id == null) {
		    if (other.id != null)
			    return false;
	    } else if (!id.equals(other.id))
		    return false;
	    return true;
    }
	
	

}
